#!/usr/bin/env python3
"""Split main.bbl into a main-body list and an appendix-only list.

See README-bib.md. Run from papers/lagarnet-TRL/ after regenerating main.bbl with BibTeX.
The appendix-only key set is derived from main.tex itself, so it stays correct as citations move.
"""
import re
import sys

MAIN_TEX = "main.tex"
BBL = "main.bbl"

NOTE = ("%% Generated by split_bib.py from main.bbl; see README-bib.md to regenerate.\n"
        "%% Do NOT edit by hand -- edit ref.bib and re-run the split.\n")


def cited_keys(text):
    keys = []
    for m in re.finditer(r"\\cite\{([^}]*)\}", text):
        keys += [k.strip() for k in m.group(1).split(",")]
    return set(keys)


def main():
    tex = open(MAIN_TEX, encoding="utf8").read()
    split_at = tex.index("\\appendices")
    appendix_only = cited_keys(tex[split_at:]) - cited_keys(tex[:split_at])

    src = open(BBL, encoding="utf8").read()
    start = src.index("\\bibitem")
    header = src[:start]
    body = src[start:src.rindex("\\end{thebibliography}")]

    idx = [m.start() for m in re.finditer(r"\\bibitem", body)]
    entries = [body[a:b] for a, b in zip(idx, idx[1:] + [len(body)])]

    def key(entry):
        return re.search(r"\\bibitem\{([^}]*)\}", entry).group(1)

    main_e = [e for e in entries if key(e) not in appendix_only]
    app_e = [e for e in entries if key(e) in appendix_only]

    # BibTeX numbers by first citation, and every appendix-only key is first cited after the
    # whole main body -- so those entries must be the trailing block. If not, the split would
    # renumber main-body citations.
    if entries[len(main_e):] != app_e:
        sys.exit("ERROR: appendix-only entries are not the trailing block of main.bbl; "
                 "splitting here would renumber main-body citations.")

    open("refs-main.tex", "w", encoding="utf8").write(
        NOTE + header + "".join(main_e) + "\\end{thebibliography}\n")
    open("refs-appendix.tex", "w", encoding="utf8").write(
        NOTE + "\\begin{thebibliography}{10}\n"
        + "\\setcounter{enumiv}{%d}\n" % len(main_e)
        + "".join(app_e) + "\\end{thebibliography}\n")

    print("refs-main.tex     : %d entries [1]-[%d]" % (len(main_e), len(main_e)))
    print("refs-appendix.tex : %d entries [%d]-[%d]"
          % (len(app_e), len(main_e) + 1, len(entries)))


if __name__ == "__main__":
    main()
