name: image2state-sac
device: "cuda:0"
replay_device: Disk

exp_name: ${exp_name}
project_name: ${project_name}

# === Inputs ===
obs_keys: ['rgb']
state_keys: ['semkey_norm_pixel']
reward_key: multi_stage_reward

context_horizon: 1
each_image_shape: [3, 128, 128]   # Increased from 84x84

# === Network Dimensions ===
init_alpha: 0.1
hidden_dim: 256
state_dim: 30 # 15*2*2
feature_dim: 25
action_dim: 8
action_range: 1.0

# === Actor / Critic ===
actor_hidden_dims: [256, 256, 128]
critic_hidden_dims: [256, 256, 128]

# === GAN-like Encoder (same structure, larger input) ===
conv_layers:
  - {out_channels: 64,  kernel_size: 4, stride: 2}
  - {out_channels: 128, kernel_size: 4, stride: 2}
  - {out_channels: 256, kernel_size: 4, stride: 2}
  - {out_channels: 512, kernel_size: 3, stride: 1}
  - {out_channels: 512, kernel_size: 3, stride: 1}

# === Optimizers ===
actor_lr: 3e-4
critic_lr: 3e-4
encoder_lr: 3e-4
alpha_lr: 3e-4

# === SAC Hyperparametersk ===
tau: 0.005
gamma: 0.99
batch_size: 256
replay_capacity: 100000
initial_act_steps: 100
train_freq: 1
gradient_steps: 2
target_update_interval: 1

# === Training Schedule ===
total_update_steps: 100000
validation_interval: 1000
eval_checkpoint: -1
