name: image2state-sac
device: "cuda:1"   # fallback to cuda:0


obs_keys: ['rgb']
state_keys: ['semkey_pos']
reward_key: coverage_alignment_with_stretch_penality_high_coverage_bonus

context_horizon: 1
each_image_shape: [3, 84, 84]

hidden_dim: 256
state_dim: 45 #3*15
feature_dim: 30 #512
action_dim: 8
action_range: 1.0

actor_lr: 3e-4
critic_lr: 3e-4
encoder_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 100000 
initial_act_steps: 100
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 100000
validation_interval: 1000
eval_checkpoint: -1