name: image-based-multi-primitive-sac
device: ${oc.env:DEVICE,cuda:0}   # fallback to cuda:0
encoder:
  out_dim: 256
  cnn_channels: [32, 64, 128]
  kernel: 3
  pool: 2
obs_key: rgb

context_horizon: 4
each_image_shape: [3, 64, 64]
num_primitives: 4
hidden_dim: 256

actor_lr: 3e-4
critic_lr: 3e-4
encoder_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 100000
initial_act_steps: 100
max_grad_norm: 10.0
save_dir: null
act_steps_per_update: 1
action_dims: [4, 8, 6, 8]
primitive_param:
  - [norm-pixel-pick-and-fling, [[pick_0, 2], [pick_1, 2]]]
  - [norm-pixel-pick-and-place, [[pick_0, 2], [pick_1, 2], [place_0, 2], [place_1, 2]]]
  - [norm-pixel-pick-and-drag, [[pick_0, 2], [pick_1, 2], [place_0, 2]]]
  - [norm-pixel-fold, [[pick_0, 2], [pick_1, 2], [place_0, 2], [place_1, 2]]]

reward_key: multi_stage_reward
add_reject_actions: true
reject_action_reward: -1
total_update_steps: 100000
explore_mode: e-greedy

validation_interval: 1000
eval_checkpoint: -1