name: multi-primitive-diffusion
oracle: False # TODO: fix this, I need to add this because of build_agent function
obs_dim: 512
action_dim: 8
obs_horizon: 1
pred_horizon: 1
num_diffusion_iters: 100
action_horizon: 1
input_obs: 'rgb'
use_mask: False
eval_action_sampler: 'normal'
include_state: False
num_demos: 2
batch_size: 4
disable_updown: True
collect_on_success: False
action_shape: [8]
data_obs: 'image'
data_state: 'agent_pos'
data_action: 'action'
train_mode: 'from_policy'
demo_policy: "human-multi-primitive"
validation_interval: 10
total_update_steps: 20
eval_checkpoint: -1
debug: False
add_all_demos: True

dataset_mode: "general"
dataset_config:
  data_path: "multi_longsleeve_folding_from_crumpled_human_multi_primitive_test"
  data_dir: "./data/datasets"
  seq_length: 1
  io_mode: "w"
  obs_config:
    mask: 
      shape: [128, 128, 1]
      output_key: 'mask'
    
    depth: 
      shape: [128, 128, 1]
      output_key: 'depth'
    
    rgb: 
      shape: [128, 128, 3]
      output_key: 'rgb'

  act_config:
    default: 
      shape: [9]
      output_key: 'default'

primitive_integration: 'predict_bin_as_output'
primitives:
  - name: norm-pixel-pick-and-fling
    dim: 4 # [pick_0, pick_1]
  - name: norm-pixel-fold
    dim: 8 #params: [pick_0, pick_1, place_0, place_1]

exp_name: ${exp_name}
project_name: ${project_name}