name: image2state-multi-primitive-sac
device: ${oc.env:DEVICE,cuda:1}   # fallback to cuda:0
replay_device: Disk

exp_name: ${exp_name}
project_name: ${project_name}

primitive_integration: 'predict_bin_as_output'

obs_keys: ['state']
reward_key: last_reward_with_affordance_penalty

obs_type: "state"
init_alpha: 0.1
context_horizon: 1
hidden_dim: 256
state_dim: 21
action_range: 1.0
reward_scale: 1


actor_lr: 3e-5
critic_lr: 3e-5
alpha_lr: 3e-5
tau: 0.001
gamma: 0.99
batch_size: 1024

replay_capacity: 1000000 
initial_act_steps: 3000 #10000
train_freq: 1
gradient_steps: 1 #1
target_update_interval: 1

total_update_steps: 2000000
validation_interval: 10000
eval_checkpoint: -1


# === GAN-like Encoder (same structure, larger input) ===
conv_layers:
  - {out_channels: 64,  kernel_size: 4, stride: 2}
  - {out_channels: 128, kernel_size: 4, stride: 2}
  - {out_channels: 256, kernel_size: 4, stride: 2}
  - {out_channels: 512, kernel_size: 3, stride: 1}
  - {out_channels: 512, kernel_size: 3, stride: 1}

use_decoder: true

decoder_layers:
  - {out_channels: 512, kernel_size: 3, stride: 1, padding: 0}
  - {out_channels: 256, kernel_size: 3, stride: 1, padding: 0}
  - {out_channels: 128, kernel_size: 4, stride: 2, padding: 1}
  - {out_channels: 64,  kernel_size: 4, stride: 2, padding: 1}
  - {out_channels: 3,   kernel_size: 4, stride: 2, padding: 1}

state_loss_coef: 0.1
recon_loss_coef: 2
encoder_max_grad_norm: 5

primitives:
  - name: reach
    dim: 4 #x, y, z, gripper_yaw
  - name: atomic
    dim: 5 #x, y, z, gripper_yaw, gripper_open_close
  - name: push
    dim: 7 #x, y, z, grippre_yaw, dx, dy, dz
  - name: grasp
    dim: 4 #x, y, z, gripper_yaw
  - name: open
    dim: 0 # no parameter 