name: vanilla-sac
device: ${oc.env:DEVICE,cuda:0}   # fallback to cuda:0


obs_keys: ['semkey_pos', 'flattened_semkey_pos']
reward_key: coverage_alignment_with_stretch_penality_high_coverage_bonus

context_horizon: 1

hidden_dim: 256
state_dim: 90 #3*15*2
action_dim: 8
action_range: 1.0
init_alpha: 0.1

actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 100
initial_act_steps: 3
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 1000
validation_interval: 5
eval_checkpoint: -1