name: vanilla-sac
device: ${oc.env:DEVICE,cuda:1}   # fallback to cuda:0


obs_keys: ['state']
reward_key: default
init_alpha: 1 #0.1
auto_alpha_learning: True
context_horizon: 1

hidden_dim: 256
state_dim: 42 #3*15
action_dim: 7
action_range: 1.0
critic_grad_clip_value: 10.0
actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256 #256

replay_capacity: 1000000 
initial_act_steps: 10000
train_freq: 1
gradient_steps: 1 #1
target_update_interval: 1

total_update_steps: 1000000
validation_interval: 10000
eval_checkpoint: -1