name: primitive-encoding-sac
device: ${oc.env:DEVICE,cuda:1}   # fallback to cuda:0
replay_device: Disk

exp_name: ${exp_name}
project_name: ${project_name}

obs_keys: [semkey_pos]
reward_key: coverage_alignment_with_stretch_penalty_high_coverage_bonus

update_temperature: 0.01 #1.0
sampling_temperature: 1.0
init_alpha: 0.1
# critic_grad_clip_value: 1.0
detach_unused_action_params: True
one_hot_scalar: 0.1
context_horizon: 1
hidden_dim: 256
state_dim: 45
action_dims: [4, 8]
action_range: 1.0
num_primitives: 2


actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 100000 
initial_act_steps: 100
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 100000
validation_interval: 1000
eval_checkpoint: -1


primitives:
  - name: norm-pixel-pick-and-fling
    dim: 4 # [pick_0, pick_1]
  - name: norm-pixel-fold
    dim: 8 #params: [pick_0, pick_1, place_0, place_1]