name: primitive-encoding-sac
device: ${oc.env:DEVICE,cuda:0}   # fallback to cuda:0


obs_keys: [semkey_pos]
reward_key: coverage_alignment_with_stretch_penality_high_coverage_bonus
update_temperature: 0.01 # Too close to 0, it can become softmax
sampling_temperature: 1

context_horizon: 1
one_hot_scalar: 1

hidden_dim: 256
state_dim: 45
action_dims: [8]
action_range: 1.0
num_primitives: 1
primitive_param:
  - name: norm-pixel-fold
    params:
      - [pick_0, 2]
      - [pick_1, 2]
      - [place_0, 2]
      - [place_1, 2]

actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 4 #256

replay_capacity: 100 #100000 
initial_act_steps: 10 #100
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 1000 #100000
validation_interval: 100 #1000
eval_checkpoint: -1