name: vanilla-image-sac
device: ${oc.env:DEVICE,cuda:0}   # fallback to cuda:0


obs_key: rgb
reward_key: coverage_alignment_with_stretch_penality_high_coverage_bonus

context_horizon: 1

hidden_dim: 256
feature_dim: 512
action_dim: 8
action_range: 1.0

actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 100000 
initial_act_steps: 100
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 100000
validation_interval: 1000
eval_checkpoint: -1