obs_dim: 512
action_dim: 8
obs_horizon: 1
pred_horizon: 1
num_diffusion_iters: 100
action_horizon: 1
input_obs: 'depth'
use_mask: True
eval_action_sampler: 'normal'
include_state: False
num_demos: 100
batch_size: 64

# readjust_pick: True
data_obs: 'image'
data_state: 'agent_pos'
data_action: 'action'
train_mode: 'from_policy'
demo_policy: "centre_sleeve_folding_stochastic_policy"
# num_epochs: 100

logger_name: 'pick_and_place_fabric_single_task_logger'


dataset_mode: "general"
dataset_config:
  data_path: "single_longsleeve_folding_from_flattened_100"
  data_dir: "./data/"
  seq_length: 1
  obs_config:
    mask: 
      shape: [128, 128, 1]
      output_key: 'mask'
    
    depth: 
      shape: [128, 128, 1]
      output_key: 'depth'
    
    rgb: 
      shape: [128, 128, 3]
      output_key: 'rgb'

  act_config:
    norm-pixel-fold: 
      shape: [8]
      output_key: 'default'

data_augmenter:
  params:
    img_dim: [96, 96]
    remap_image: [0, 1]
    device: "cuda:0"
    rgb_norm_mode: ['remap']
    rgb_norm_param:
      remap_range: [0, 1]
    rgb_noise_factor: 0.01
    random_rotation: True
    random_terminal: False
    rotation_degree: 1
    vertical_flip: False
    random_resize: False
    action_noise: 0.0
    depth_clip: True
    depth_clip_min: 1.8 #
    depth_clip_max: 2.0 #0.66
    min_max_norm: True
    depth_min: 1.8
    depth_max: 2.0
    depth_map: True
    depth_map_range: [0, 1]
    depth_blur: True
    depth_flip: True
    depth_blur_kernel_size: 2
    depth_noise_var: 0.01
    depth_eval_process: True
    maskout: True
    bg_value: 0
    debug: False
    primitive: "norm-pixel-fold"

disable_updown: True
swap_pick_and_place: True
action_shape: [8]

action_output:
  norm-pixel-fold:
    pick_0: [0, 1]
    place_0: [2, 3]
    pick_1: [4, 5]
    place_1: [6, 7]
    
action_save:
  norm-pixel-fold:
    pick_0: [0, 1]
    place_0: [2, 3]
    pick_1: [4, 5]
    place_1: [6, 7]