name: magpie
device: 'cuda'
oracle: False # TODO: fix this, I need to add this because of build_agent function
action_dim: 8
obs_horizon: 1
pred_horizon: 1
action_horizon: 1
input_obs: 'rgb+goal_rgb'
use_mask: True
eval_action_sampler: 'normal'
include_state: False
num_demos: 800
demo_horizon: 10

disable_updown: True
action_shape: [8]
collect_on_success: False # This is important!
data_obs: 'image'
data_state: 'agent_pos'
data_action: 'action'
train_mode: 'from_policy'
demo_policy: "human-multi-primitive"
demo_policy_config:
  overlay_goal_contour: True
  
validation_interval: 5000
val_interval: 100
validate_training: True

total_update_steps: 100000
eval_checkpoint: -1
debug: False
add_all_demos: True

## it learns to predict the states from the obs embedding.

dataset_mode: "general"
dataset_config:
  data_path: "all_garments_multi_primitive_alignment"
  data_dir: "./data/datasets"
  split_ratios: [0.0, 0.05, 0.95]
  seq_length: 1
  io_mode: "w"
  cache_in_memory: True

  obs_config:
    
    mask: 
      shape: [128, 128, 1]
      output_key: 'mask'
    
    depth: 
      shape: [128, 128, 1]
      output_key: 'depth'
    
    rgb: 
      shape: [128, 128, 3]
      output_key: 'rgb'

    semkey_norm_pixel:
      shape: [17, 2]
      output_key: 'semkey_norm_pixel'

    goal_rgb: 
      shape: [128, 128, 3]
      output_key: 'goal_rgb'
    
    goal_depth: 
      shape: [128, 128, 1]
      output_key: 'goal_depth'
    
    goal_mask: 
      shape: [128, 128, 1]
      output_key: 'goal_mask'

    flattened_semkey_norm_pixel:
      shape: [17, 2]
      output_key: 'flattened_goal_semkey_norm_pixel'


  act_config:
    default: 
      shape: [9]
      output_key: 'default'


loss_type: 'ot_flow_match'
num_diffusion_iters: 10

noise_pred_net: 'mlp'
mlp_backbone_config:
  hidden_dims: [1024, 1024, 1024, 512]
  activation: 'gelu'
  dropout: 0.1

primitive_integration: 'separate_networks'
primitive_classifier:
  hidden_dims: [128]
  activation: relu        # relu | gelu | silu | tanh | leaky_relu
  dropout: 0.5          # 0.0 to disable
  use_layernorm: true
prim_class_weights: [1.0, 1.0, 1.0, 1.0]
prim_weight: 0.01

## Following is the parameter from the fast conditional decoupling paper
batch_size: 256
optimiser_class: 'adamw'
optimiser_params: 
  lr: 1e-4
  weight_decay: 1e-2
num_warmup_steps: 1500
ema_power: 0.9999

primitives:
  - name: norm-pixel-pick-and-fling
    dim: 4 # [pick_0, pick_1]
  - name: norm-pixel-dual-pick-and-place
    dim: 8 #params: [pick_0, pick_1, place_0, place_1]
  - name: norm-pixel-single-pick-and-place
    dim: 4 #params: [pick_0, place_0]
  - name: no-operation
    dim: 0
mask_out_irrelavent_action_dim: true

vision_encoder: 'original'
obs_dim: 512

use_projector: True
projector_hidden_dims: [256, 256] # Can be empty [] for a direct linear mapping
projector_out_dim: 256 
projector_activation: 'relu'
projector_dropout: 0.0
projector_use_layernorm: False
feature_noise_factor: 0.01

predict_goal_state: False

data_augmenter: pixel_based_multi_primitive_augmenter_for_diffusion_colour_jittering_channel_permuation_K_4_goal_sem_key_with_rotate_swap_index_random_scale