name: magpie
device: 'cuda'
oracle: False
action_dim: 8
obs_horizon: 1
pred_horizon: 1
action_horizon: 1
input_obs: 'rgb+goal_rgb'
use_mask: True
eval_action_sampler: 'normal'
include_state: False
num_demos: 800
demo_horizon: 10

disable_updown: True
action_shape: [8]
collect_on_success: False 
data_obs: 'image'
data_state: 'agent_pos'
data_action: 'action'
train_mode: 'from_policy'
demo_policy: "human-multi-primitive"
demo_policy_config:
  overlay_goal_contour: True
  
validation_interval: 5000
val_interval: 1000
validate_training: True

total_update_steps: 120000
grad_clip_norm: 1.0
eval_checkpoint: -1
debug: False
add_all_demos: True

dataset_mode: "hindsight"
dataset_config:
  data_path: "all_garments_multi_primitive_alignment"
  data_dir: "./data/datasets"
  split_ratios: [0.0, 0.05, 0.95]
  seq_length: 1
  io_mode: "w"
  cache_in_memory: True

  future_goal_mapping:
    rgb: 'goal_rgb'
    depth: 'goal_depth'
    mask: 'goal_mask'
    semkey_norm_pixel: 'flattened_goal_semkey_norm_pixel'
    
  obs_config:
    mask: { shape: [128, 128, 1], output_key: 'mask' }
    depth: { shape: [128, 128, 1], output_key: 'depth' }
    rgb: { shape: [128, 128, 3], output_key: 'rgb' }
    semkey_norm_pixel: { shape: [17, 2], output_key: 'semkey_norm_pixel' }
    goal_rgb: { shape: [128, 128, 3], output_key: 'goal_rgb' }
    goal_depth: { shape: [128, 128, 1], output_key: 'goal_depth' }
    goal_mask: { shape: [128, 128, 1], output_key: 'goal_mask' }
    flattened_semkey_norm_pixel: { shape: [17, 2], output_key: 'flattened_goal_semkey_norm_pixel' }

  act_config:
    default: { shape: [9], output_key: 'default' }

loss_type: 'ot_flow_match'
num_diffusion_iters: 4

noise_pred_net: 'mlp'
mlp_backbone_config:
  hidden_dims: [1024, 1024, 1024, 512]
  activation: 'gelu'
  dropout: 0.1

primitive_integration: 'separate_networks'
primitive_classifier:
  hidden_dims: [256, 128]
  activation: relu        
  dropout: 0.5          
  use_layernorm: true
prim_class_weights: [1.0, 1.0, 1.0, 1.0]
prim_weight: 0.01

batch_size: 1024
optimiser_class: 'adamw'
optimiser_params: 
  lr: 3e-4
  weight_decay: 1e-2
num_warmup_steps: 3000
ema_power: 0.9999

primitives:
  - name: norm-pixel-pick-and-fling
    dim: 4 
  - name: norm-pixel-dual-pick-and-place
    dim: 8 
  - name: norm-pixel-single-pick-and-place
    dim: 4 
  - name: no-operation
    dim: 0
mask_out_irrelavent_action_dim: true

vision_encoder: 'original'
obs_dim: 512

use_projector: True
projector_hidden_dims: [512, 512]
projector_out_dim: 512
projector_activation: 'gelu'
projector_dropout: 0.0
projector_use_layernorm: False
feature_noise_factor: 0.05

predict_goal_state: False

data_augmenter: pixel_based_multi_primitive_augmenter_for_diffusion_colour_jittering_channel_permuation_K_4_goal_sem_key_with_rotate_swap_index_random_scale