# diffusion_single_picker_single_primitive_multi_longsleeve_flattening_demo_200.yaml
name: ja-tn

n_rotations: 1
in_shape: [128, 128, 1]
crop_size: 32 # has to be even
pixel2world: False
train_mode: "from_dataset"
num_train_demo_episodes: 50
num_test_demo_episodes: 3
n_sample: 50

total_update_steps: 20000
validation_interval: 5000
sl_update_steps: 20000
test_interval: 2000
batch_size: 10

action_dim: [1, 4]
encoder_version: 'resnet43'
pick_action_filter: "mask"
place_action_filter: "identity"
pick_and_place_policy: "sample"
input_obs: 'depth'
num_pick_prob_prod: 10
save_mask: True
save_contour: False

logger_name: 'pick_and_place_fabric_single_task_logger'
save_heatmap: True
verbose: True

augmentation: False

datasets:
  train:
    dataset_config:
      data_path: "multi_longsleeve_single_picker_single_primitive_flattening_human_demo_100"
      data_dir: "./data/datasets"
      seq_length: 1
      num_trj: 200
      io_mode: "r"
      cache_in_memory: True
      obs_config:
        mask: 
          shape: [128, 128, 1]
          output_key: 'mask'
        
        depth: 
          shape: [128, 128, 1]
          output_key: 'depth'
        
        rgb: 
          shape: [128, 128, 3]
          output_key: 'rgb'

      act_config:
        default: 
          shape: [4]
          output_key: 'default'
  test:
    dataset_config:
      data_path: "multi_longsleeve_single_picker_single_primitive_flattening_human_demo_100"
      data_dir: "./data/datasets"
      seq_length: 1
      num_trj: 200
      io_mode: "r"
      cache_in_memory: True
      obs_config:
        mask: 
          shape: [128, 128, 1]
          output_key: 'mask'
        
        depth: 
          shape: [128, 128, 1]
          output_key: 'depth'
        
        rgb: 
          shape: [128, 128, 3]
          output_key: 'rgb'

      act_config:
        default: 
          shape: [4]
          output_key: 'default'


attention_optimiser:
  name: 'adam'
  params:
    lr: 1e-4


key_optimiser:
  name: 'adam'
  params:
    lr: 1e-4

  
query_optimiser:
  name: 'adam'
  params:
    lr: 1e-4

transform:
  name: 'transporter_net_transformer'
  params:   
    device: "cuda:0"
    img_dim: [128, 128]
    rgb_norm_mode: ['remap']
    rgb_norm_param:
      remap_range: [0, 1]
    rgb_noise_factor: 0.02
    swap_action: True

    depth_norm_mode: ['min_max_soft', 'remap'] 
    depth_norm_param:
      min_max_range: [1.8, 2.0]
      remap_range: [0, 1]
    depth_noise_factor: 0.01
    depth_flip: True
    blur_depth: True
    maskout: True
    bg_value: 0.0
    
    random_rotation: true
    rotation_degree: 1
    vertical_flip: true